<?php
/**
 * This is the default framework theme. For most pages, this is the source of all browser output.
 * This is just an html template with some php to sprinke content around. We're using the
 * getHook() function to render hook contents from the modules/framework, and we're using the
 * get() function to get some standard text from the config.xml.
 *
 * Use setHook from your module (or anywhere within the app, really) to add something to a hook
 * referenced from this theme.
 *
 * @package MyCMS
 * @author Doug Hatcher superterran@gmail.com
 * @copyright http://creativecommons.org/licenses/by/3.0/deed.en_US
 */
?>
<!doctype>
<html>
    <head>

        <title><?php echo $this->get('site/title') . $this->getHook('title', ' - '); ?>
        </title>
        <link rel = "stylesheet" href = "<?php echo $this->get('theme/url'); ?>css/style.css">

    </head>
    <body>

        <div id = "container">

            <div id = "header">

                <img src = "<?php echo $this->get('theme/url'); ?>img/icon.png" id = "icon">

                <h1><?php echo $this->get('site/title'); ?></h1>
                <h2><?php echo $this->get('site/description'); ?></h2>
            </div>

            <div id = "content"><?php echo $this->getHook('content'); ?></div>

            <div id = "footer"><?php echo $this->get('site/footer'); ?></div>

        </div>

    </body>
</html>